version: '3'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    restart: always
    env_file: .env
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    env_file: .env
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - backend
    networks:
      - backend
  postgres:
    container_name: 'postgres'
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/data/postgres
    restart: always
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "3003:8080"
    networks:
      - backend
volumes:
    postgres_data:

networks:
  backend:
  frontend:
